name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      # Install dep
      - run: yarn install

      # Build
      - run: yarn build

      # Run tests
      - run: yarn test
        env:
          PORT: 10000
          JWT_ACCESS_TOKEN_SECRET: foekfskefoskfekoskoe
          JWT_REFRESH_TOKEN_SECRET: feoksefskofeokfs24903
          DB_URI: ${{ secrets.DB_URI }}
          NODE_ENV: test
